- name: Update Kubernetes Deployment
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_KEY }}
    script: |
      kubectl set image deployment/nginx-cicd-deployment \
      nginx-cicd-container=anu969/anu123-nginx-ci-cd:latest
